global:
  enable_gh_proxy: true
  gh_proxy: "https://v6.gh-proxy.org/"
  split_cnip: true
  singbox:      {enable: true, single_file: false, json: true, srs: true}
  mihomo:       {enable: true, single_file: false, txt: false, yaml: true, mrs: true}
  v2ray:        {enable: true, single_file: false}
  surge:        {enable: true, single_file: true}
  loon:         {enable: true, single_file: true}
  stash:        {enable: true, single_file: true}
  egern:        {enable: true, single_file: true}
  shadowrocket: {enable: true, single_file: true}
  quantumultx:  {enable: true, single_file: true}

categories:
  - name: cn
    merge_from: ["applecn"]
    publish_dnsmasq: true               #仅作示例
    publish_smartdns: true              #仅作示例
    dnsmasq_server: "223.6.6.6"         #仅作示例
    smartdns_server: "china_group"      #仅作示例
    upstreams:
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs.list"}
      - {url: "https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute.txt"}
      - {url: "https://raw.githubusercontent.com/mayaxcn/china-ip-list/master/chnroute_v6.txt"}
      - {url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaIp.list"}
      - {url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaIpV6.list"}
      - {url: "https://ispip.clang.cn/all_cn_ipv46.txt"}

  - name: reject
    auto_extract_white: true
    publish_white: true
    white_behavior: "remove"
    publish_adblock: true
    publish_dnsmasq: true
    publish_smartdns: true
    remove_urls:
      - {"https://raw.githubusercontent.com/217heidai/adblockfilters/refs/heads/main/rules/white.txt"}
    upstreams:
      - {url: "https://anti-ad.net/clash.yaml"}
      - {url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml"}
      - {url: "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"}

  - name: google
    upstreams:
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/google.txt"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list"}
      - {url: "https://raw.githubusercontent.com/VPSDance/ai-proxy-rules/refs/heads/main/rules/clash/google-ai.yaml"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/google.list"}

  - name: ai
    upstreams:
      - {url: "https://raw.githubusercontent.com/QuixoticHeart/rule-set/refs/heads/ruleset/meta/ai.list"}
      - {url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ai-!cn.list"}
      - {url: "https://raw.githubusercontent.com/VPSDance/ai-proxy-rules/refs/heads/main/rules/clash/global.yaml"}

  - name: applecn
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMusic/AppleMusic.list"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"}

  - name: cloudflare
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Cloudflare/Cloudflare.list"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/geoip/refs/heads/release/clash/ipcidr/cloudflare.txt"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/cloudflare.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/cloudflare.list"}

  - name: proxy
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"}

  - name: telegram
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.list"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt"}

  - name: twitter
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/twitter.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/twitter.list"}

  - name: meta
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/meta.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Threads/Threads.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Instagram/Instagram.list"}

  - name: gits
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitBook/GitBook.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gitee/Gitee.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitLab/GitLab.list"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list"}

  - name: tiktok
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/tiktok.list"}

  - name: discord
    upstreams:
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Discord/Discord.list"}
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/discord.list"}

  - name: httpdns
    upstreams:
      - {url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-httpdns-cn.list"}
      - {url: "https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/refs/heads/main/ruleset/HTTPDNS.Block.list"}
      - {url: "https://raw.githubusercontent.com/QuixoticHeart/rule-set/refs/heads/ruleset/meta/domain/httpdns.list"}

  - name: private
    upstreams:
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"}
      - {url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"}
      - {url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list"}

  - name: fakeipfilter
    upstreams:
      - {url: "https://raw.githubusercontent.com/QuixoticHeart/rule-set/refs/heads/ruleset/meta/domain/fake-ip-filter.list"}

  - name: webrtc
    singbox: {single_file: true}
    mihomo:  {single_file: true}